$schema: "1.0"
name: install-vscode-extensions
description: Installs VS Code extensions
author: David Watson
command: ".\\main.ps1 -extensions {{extensions}}"
parameters:
  extensions:
    type: string
    required: true
    description: |
      A list of Visual Studio Code extensions to install
documentation:
  notes: This task is used to install VS Code extensions.
  examples:
    - name: install-vscode-extensions
      description: Install VS Code extensions.
      parameters:
        extensions: A list of extension identifiers, e.g. "github.copilot,github.copilot-chat". Use "code --list-extensions" to get a list of currently installed extensions.
