$schema: "1.0"
name: install-vscode-extensions
description: Installs VS Code extensions
author: David Watson
command: ./main.ps1 -extensions {{extensions}}
parameters:
  extensions:
    type: string
    default: ""
    required: true
    description: |
      A list of Visual Studio Code extensions to install, using identifiers. e.g. "github.copilot,github.copilot-chat". Use "code --list-extensions" to get a list of currently installed extensions.
documentation:
  notes: This task is used to install VS Code extensions.
  examples:
    - name: install-vscode-extensions
      description: Install the GitHub Copilot VS Code extensions
      parameters:
        extensions: "github.copilot,github.copilot-chat"
