# From https://github.com/microsoft/devcenter-examples
$schema: "1.0"
tasks:
  - name: winget
    parameters:
      package: Microsoft.VisualStudioCode
      runAsUser: true
  - name: winget
    parameters:
      package: Microsoft.SQLServerManagementStudio
      runAsUser: true
  - name: winget
    parameters:
      package: Microsoft.Azure.StorageExplorer
      runAsUser: true
  - name: winget 
    parameters:
      package: GitExtensionsTeam.GitExtensions
      runAsUser: true
  - name: winget
    parameters:
      package: JGraph.Draw
      runAsUser: true
  - name: choco
    parameters:
      package: xrmtoolbox
  - name: install-powerplatformcli
  # - name: install-visio
  - name: install-vscode-extensions
    parameters:
      extensions: 'github.copilot,github.copilot-chat'
  - name: git-clone
    parameters:
      repositoryUrl: https://github.com/davidxw/devcenter-catalog
      directory: C:\wip


